trigger:
- main

strategy:
  matrix:
    win-chrome:
      imageName: windows-2022
      browser: chrome

pool:
  vmImage: $(imageName)

variables:
  SELENIUM_BROWSER: $(browser)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - powershell: |
      if ($env:SELENIUM_BROWSER -eq "chrome") {
        # Download AutoIt
        Invoke-WebRequest -Uri 'https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe' -OutFile 'AutoIt-Setup.exe'
        # Install AutoIt silently
        Start-Process -Wait -FilePath '.\AutoIt-Setup.exe' -ArgumentList '/S'
      }
    displayName: 'Install AutoIt'

  - script: |
      if [ "$(SELENIUM_BROWSER)" == "chrome" ]; then
        # Start Chrome in visible mode
        start chrome
      fi
    displayName: 'Start Chrome'

  - script: npm install
    displayName: 'Installing node-modules'

  - script: npm install chromedriver
    displayName: 'Install ChromeDriver'

  - script: npm run wdio
    displayName: 'Running the test cases'

  - script: |
      if [ "$(SELENIUM_BROWSER)" == "chrome" ]; then
        # Close Chrome
        taskkill /IM chrome.exe /F
      fi
    displayName: 'Close Chrome'
