trigger:
- main

strategy:
  matrix:
    win-chrome:
      imageName: windows-2022
      browser: chrome

pool:
  vmImage: $(imageName)

variables:
  SELENIUM_BROWSER: $(browser)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      if [ "$(SELENIUM_BROWSER)" == "chrome" ]; then
        # Download AutoIt
        wget https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -O AutoIt-Setup.exe
        # Install AutoIt silently
        AutoIt-Setup.exe /S
      fi
    displayName: 'Install AutoIt'

  - script: |
      if [ "$(SELENIUM_BROWSER)" == "chrome" ]; then
        # Start Chrome in visible mode
        start chrome
      fi
    displayName: 'Start Chrome'

  - script: npm install
    displayName: 'Installing node-modules'

  - script: npm install chromedriver
    displayName: 'Install ChromeDriver'

  - script: npm run wdio
    displayName: 'Running the test cases'

  - script: |
      if [ "$(SELENIUM_BROWSER)" == "chrome" ]; then
        # Close Chrome
        taskkill /IM chrome.exe /F
      fi
    displayName: 'Close Chrome'
