trigger:
- main

pr:
- '*'

jobs:
- job: RunWebioTests
  pool:
    vmImage: 'windows-latest'  # Use a Windows image
  strategy:
    matrix:
      win-chrome:
        SeleniumBrowser: chrome
    maxParallel: 1

  steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: 18.x  # Use Node.js version 18.x

  - powershell: |
      if ($(SeleniumBrowser) -eq "chrome") {
        # Download and install AutoIt (for handling browser dialogs)
        Invoke-WebRequest -Uri 'https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe' -OutFile 'AutoIt-Setup.exe'
        Start-Process -Wait -FilePath '.\AutoIt-Setup.exe' -ArgumentList '/S'
      }
    displayName: 'Install AutoIt'

  - script: |
      if "%SeleniumBrowser%"=="chrome" (
        Start-Process "chrome.exe" -Wait
        # start chrome
      )
    displayName: 'Start Chrome'

  - script: npm install  # Install your project dependencies
    displayName: 'Install Node Modules'

  - script: npm install chromedriver  # Install ChromeDriver
    displayName: 'Install ChromeDriver'

  - script: npm run wdio  # Run your WebDriverIO tests
    displayName: 'Running WebDriverIO tests'

  - powershell: |
      if ($(SeleniumBrowser) -eq "chrome") {
        # Close Chrome browser after tests
        taskkill /IM chrome.exe /F
      }
    displayName: 'Close Chrome'
