trigger:
- main

strategy:
  matrix:
    win-chrome:
      imageName: windows-2022
      browser: chrome

pool:
  vmImage: $(imageName)

variables:
  SELENIUM_BROWSER: $(browser)

steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: 18.x

  - powershell: |
      if ($env:SELENIUM_BROWSER -eq "chrome") {
        # Download AutoIt
        Invoke-WebRequest -Uri 'https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe' -OutFile 'AutoIt-Setup.exe'
        # Install AutoIt silently
        Start-Process -Wait -FilePath '.\AutoIt-Setup.exe' -ArgumentList '/S'
      }
    displayName: 'Install AutoIt'

  - script: |
      if "%SELENIUM_BROWSER%"=="chrome" (
        start chrome
      )
    displayName: 'Start Chrome'

  - script: npm install
    displayName: 'Installing node-modules'

  - script: npm install chromedriver
    displayName: 'Install ChromeDriver'

  - script: npm run wdio
    displayName: 'Running the test cases'

  - script: |
      if "%SELENIUM_BROWSER%"=="chrome" (
        taskkill /IM chrome.exe /F
      )
    displayName: 'Close Chrome'

  - task: UseJavaVersion@0
    displayName: 'Set up Java'
    inputs:
      version: '8'

  - script: |
      # Download and install Katalon Studio
      Invoke-WebRequest -Uri 'https://download.katalon.io/8.2.3/Katalon_Studio_Windows_64-8.2.3.zip' -OutFile 'Katalon_Studio.zip'
      Expand-Archive -Path 'Katalon_Studio.zip' -DestinationPath 'C:\Katalon'
    displayName: 'Install Katalon Studio'

  - script: 'C:\Katalon\katalon.exe -runMode=console -projectPath="C:\path\to\your\Katalon\project" -testSuitePath="Test Suites/YourTestSuite" -apiKey=YOUR_API_KEY'
    displayName: 'Run Katalon Studio Test Suite'
