trigger:
- main


jobs:
- job: RunWebioTests

  strategy:
   matrix:
    win-chrome:
      imageName: windows-2022
      browser: chrome

  pool:
    vmImage: 'windows-latest'  # Use a Windows image
    
    SELENIUM_BROWSER: $(browser)
  steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      version: 18.x  # You can adjust the Node.js version as needed

  - powershell: |
      if ($env:SELENIUM_BROWSER -eq "chrome") {
        # Download and install AutoIt (for handling browser dialogs)
        Invoke-WebRequest -Uri 'https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe' -OutFile 'AutoIt-Setup.exe'
        Start-Process -Wait -FilePath '.\AutoIt-Setup.exe' -ArgumentList '/S'
      }
    displayName: 'Install AutoIt'

  - powershell: Start-Process chrome.exe -Wait  # Start Chrome browser
    displayName: 'Start Chrome'

  - script: npm install  # Install your project dependencies
    displayName: 'Install Node Modules'

  - script: npm install chromedriver  # Install ChromeDriver
    displayName: 'Install ChromeDriver'

  - script: npm run wdio  # Run your WebDriverIO tests
    displayName: 'Running WebDriverIO tests'

  - powershell: |
      if ($(SeleniumBrowser) -eq "chrome") {
        # Close Chrome browser after tests
        Stop-Process -Name chrome -Force
      }
    displayName: 'Close Chrome'
